<?php 
/**
 * Pacific NM (https://www.pacificnm.com)
 *
 * @link      https://github.com/pacificnm/pacificnm-acl-resource for the canonical source repository
 * @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
 * @license BSD-3-Clause
 */
?>
<form method="get" class="form-horizontal">
	<div class="modal fade" tabindex="-1" role="dialog" id="acl-resource-search">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"
						aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<h4 class="modal-title">
						<i class="fa fa-lock" aria-hidden="true"></i>
					<?php echo $this->translate('Acl Resource Search'); ?></h4>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<label for="aclResourceName" class="col-sm-2 control-label"><?php echo $this->translate('Resource'); ?>:</label>
						<div class="col-sm-10">
							<input type="text" class="form-control" id="aclResourceName" name="aclResourceName"
							<?php if(array_key_exists('aclResourceName', $this->queryParams) && ! is_null($this->queryParams['aclResourceName'])):?>
								value="<?php echo $this->queryParams['aclResourceName']; ?>"
							<?php endif;?>
							>
						</div>
					</div>
				
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close'); ?></button>
					<button type="submit" class="btn btn-primary"><?php echo $this->translate('Search'); ?></button>
				</div>
			</div>
		</div>
	</div>
</form>